server:
  port: 8080
spring:
  application:
    name: /magic_web
  datasource:
    username: root
    password: @q8491509
    url: jdbc:mysql://cdb-fbmh1s1a.cd.tencentcdb.com:10016/cms?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 50
    minIdle: 100
    maxActive: 200
    maxWait: 6000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    removeAbandoned: true
    removeAbandonedTimeout: 60
    logAbandoned: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java







